### ISSUE TITLE
functionality required

### ISSUE THREAD

**Issue by aviadtzemah** [talkad/MAANE#11]
**this will keep updating, so check it every now and then**

tal:
- [x] given a survey id, get a survey.
- [x] a survey will have an id which is a long random combination of characters and not just numbers.
- [x] the response upon logging in needs to also include the username.
- [x] given a survey id, get its constraint rules
- [x] given a survey id and new rules update the survey rules

shaked:
- [x] given a supervisor/system manager, get all the user she created (with all the relevant info to show).
- [x] given a general supervisor, get what are his viewing permissions (will be useful to get it in the same request with the point above).
- [x] given a supervisor, get all the surveys she created (not the whole surveys, just their title and description with their id).
- [x] i can log in multiple times with the same user (that's an issue not a requirement).
- [x] change the admin username and password to "admin" and "admin"
- [x] option to change a password for a user
- [x] option to register a supervisor
- [x] admin can't register a user

shaked and almog:
- [x] format of the events of the work plan calendar is a list of the following structures: { title: String, start: Date, end: Date, allDay: boolean, resource: any}. The date can be (i think) any date format available [here](https://momentjs.com/). and resource is any resource the event may be a related too (still not sure what it means, you can put an empty string in the meantime)

**Comment by talkad** [comment]
the first function in my list is related to @shaked6

**Comment by aviadtzemah** [comment]
you still need to implement the second half of the requirement, don't you @talkad?

regardless, I moved it to @shaked6

**Comment by talkad** [comment]
If you were checking just a little, you could see that this function is already implemented. And surprisingly called getSurvey

**Comment by aviadtzemah** [comment]
![](https://media4.giphy.com/media/6f15PceJUw8WGlj4uu/giphy.gif?cid=ecf05e4761i5ncpjyu2y1sl7nut5llbwfh9pb1byxmzv9fin&rid=giphy.gif&ct=g)
