### ISSUE TITLE
calendar representation 

### ISSUE THREAD

**Issue by talkad** [talkad/MAANE#12]
Map<String, List  < Activity >> calendar;

- [ ] when (currently) Activity will be an object with two fields - schoolID and title 
- [ ] function that receives month index (January - 1 , feb - 2 ...) and returns Map<String, List < Activity > > when the dates are from the given month

**Comment by almda** [comment]
returns <String , List (Activity)>  you meant List<String, List (Activity) >?
cuz there are many dates from this month till the end of the year (the string is date)

**Comment by talkad** [comment]
Map<String, List < Activity > >
when the date string is date in the given month and the list of activities are the same

**Comment by almda** [comment]
@talkad the function you wanted called getScheduleFromMonth (String month)
Activity class added to UserManagment
done all adaptations to workplan
added tests for the above
