### ISSUE TITLE
Survey - DB

### ISSUE THREAD

**Issue by talkad** [talkad/MAANE#18]
- [x] implement the todos in SurveyQueries
- [x] create a mock DB for testing i.e. for every controller in the persistence create an interface it should implement, and create a mock controller which saves the data in Maps or Lists instead of in actual DB - ill do it
- [x] I created a cache in the SurveyController, it should be in the persistence

**Comment by almda** [comment]
Q:
- when Rule is deleted, does all his subRules need to be deleted too?
- in GetRules, does Integer represents goal id? (the integer inside Pair)
- i guess that public List<String> getSurveyTitles(List<String> result) 
 should be ==> public List<String> getSurveyTitles(String surveyId) ?
 please confirm / decline 
- SurveyAnswersDTO - id is surveyId and symbol is school symbol? please confirm / decline

**Comment by talkad** [comment]
A:
- yes
- it's the surveyID the rules belong to
- No, The list<String> is all the surveyIDs that a specific user created (you may change the name of the functions to getSurveysTitles)
- confirm

**Comment by almda** [comment]
Q: 
public Map<String, List<SurveyAnswersDTO>> getAllAnswers() ==> string is school symbol?

**Comment by talkad** [comment]
A: 
I checked and no one uses this function, so you can ignore it.

**Comment by almda** [comment]
all todo's done
